### ISSUE TITLE
About the example.

### ISSUE THREAD

**Issue by Gatsby23** [robotics-upo/plane_detector#2]
Could you please give a example about how to run this code ? I have just run :
```
roslaunch plane_seg test.launch
```
and 
```
rosbag play tum_dataset.bag
```
But, I can't see the results in the rviz. But I coudn't find out what's run with the test.launch

**Comment by david-alejo** [comment]
Dear gatsby23, thank you for your interest in this tool.

The test file is prepared with the following arguments that you should adjust in order to make it work:

- bag_file: you don't need to manually use rosbag, it is included in the launch file. Specify the **absolute route** to the bag file here.
- camera: by default we use "/front" camera. However you can change it here. You can see the prefix of the camera by using "rosbag info <bag_file>". Note that you need a RGB-D camera (with range information).

One example if the bag is in your HOME directory could be:

roslaunch plane_detector test.launch camera:=/camera bag_file:=$HOME/tum_dataset.bag

Please provide me with the "rosbag info" details of your bag, so that I can further assist you. 

Best regards,

**Comment by Gatsby23** [comment]
> Dear gatsby23, thank you for your interest in this tool.
> 
> The test file is prepared with the following arguments that you should adjust in order to make it work:
> 
> * bag_file: you don't need to manually use rosbag, it is included in the launch file. Specify the **absolute route** to the bag file here.
> * camera: by default we use "/front" camera. However you can change it here. You can see the prefix of the camera by using "rosbag info <bag_file>". Note that you need a RGB-D camera (with range information).
> 
> One example if the bag is in your HOME directory could be:
> 
> roslaunch plane_detector test.launch camera:=/camera bag_file:=$HOME/tum_dataset.bag
> 
> Please provide me with the "rosbag info" details of your bag, so that I can further assist you.
> 
> Best regards,

Thank you very much, I have already changed the dataset address in the test.launch, like this:
![Screenshot from 2021-09-09 15-53-21](https://user-images.githubusercontent.com/18000675/132645932-8d3d4a46-e3ae-4065-a2c8-4c0ac9057947.png)
But when I run the code, it like this: 
![Screenshot from 2021-09-09 15-55-10](https://user-images.githubusercontent.com/18000675/132646112-5802b6a3-bd90-49bb-8193-492aeba0509d.png)
And the rviz hasn't shown anything.
The rosbag info like this:
![Screenshot from 2021-09-09 15-56-24](https://user-images.githubusercontent.com/18000675/132646373-fdcd4343-cb2a-4e6b-aeb6-23805e9fb068.png)
Really thanks for your help. Thank you very much!

**Comment by david-alejo** [comment]
Dear Gatsby.
I'm sorry for the late reply.

It seems that the problem is due to the depth images.

If you see the line under the #Uncompress depth comment, it is trying to find the topic:

$(arg camera)/depth_registered/image_raw

However in the bag the topic of the image is:

/camera/depth/image

Try to change it and it should work.

Best regards,

**Comment by david-alejo** [comment]
Closing it because of inactivity
